spring:
  datasource:
    url: jdbc:mysql:///mydb?serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:com.qf.dao/*.xml
  type-aliases-package: com.qf.entity